# Generated by Django 5.0.4 on 2024-04-22 10:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='status',
            field=models.CharField(choices=[('생성', '생성'), ('대기', '대기'), ('실행중', '실행중'), ('완료', '완료')], default='생성', max_length=10),
        ),
    ]
